# Generated by Django 5.0.3 on 2026-03-29 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bet_types',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=50)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('cashed_out', 'Cashed Out')], default='pending', max_length=20)),
                ('is_parlay', models.BooleanField(default=False)),
                ('parlay_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('bet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.bettype')),
            ],
            options={
                'db_table': 'bets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_odds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_stake', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('potential_win', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bets', models.ManyToManyField(related_name='bet_slips', to='betting.bet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bet_slips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status'], name='bets_user_id_9b6bce_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['match', 'status'], name='bets_match_i_5b0f33_idx'),
        ),
    ]
