# Generated by Django 5.0.3 on 2026-04-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betslip',
            name='bets',
        ),
        migrations.RemoveField(
            model_name='betslip',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='betslip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bet',
            name='slip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.betslip'),
        ),
        migrations.AddField(
            model_name='betslip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cashed_out', 'Cashed Out')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='potential_win',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='total_odds',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='betslip',
            name='total_stake',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
