# Generated by Django 5.0.3 on 2026-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_remove_betslip_bets_remove_betslip_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='potential_win',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
