# Generated by Django 5.0.3 on 2026-04-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='external_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
