# Generated by Django 5.0.3 on 2026-04-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_league_external_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
