# Generated by Django 5.0.3 on 2026-06-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='source',
            field=models.CharField(choices=[('external', 'External API'), ('local', 'Local')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='source',
            field=models.CharField(choices=[('external', 'External API'), ('local', 'Local')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='source',
            field=models.CharField(choices=[('external', 'External API'), ('local', 'Local')], default='local', max_length=20),
        ),
    ]
