# Generated by Django 5.0.3 on 2026-06-02 17:01

import apps.wallet.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_currencies'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default=apps.wallet.models.get_default_currency, on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='accounts.currency'),
        ),
    ]
