# Generated by Django 5.0.3 on 2026-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_stake', 'Bet Stake'), ('bet_payout', 'Bet Payout'), ('refund', 'Refund')], default='deposit', max_length=20),
        ),
    ]
