# Generated by Django 5.0.3 on 2026-05-17 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashGameRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.BigIntegerField(editable=False, unique=True)),
                ('crash_point', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('lobby', 'Lobby (Accepting Bets)'), ('running', 'Plane Flying'), ('crashed', 'Crashed')], default='lobby', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crash_game_rounds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrashBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('cashed_out', 'Cashed Out'), ('lost', 'Lost')], default='placed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashed_out_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash_bets', to=settings.AUTH_USER_MODEL)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='casino.crashgameround')),
            ],
            options={
                'db_table': 'crash_bets',
                'indexes': [models.Index(fields=['user', 'status'], name='crash_bets_user_id_31a34f_idx'), models.Index(fields=['game_round'], name='crash_bets_game_ro_c732ec_idx')],
            },
        ),
    ]
